### ISSUE TITLE
 Entity 'eacute' not defined

### ISSUE THREAD

**Issue by middleJack** [zendframework/zend-feed#106]
### Code to reproduce the issue

```php
use Zend\Feed\Reader\Reader;
use Zend\Feed\Reader\Exception\RuntimeException;

$output = Reader::import("http://www.ejercitos.org/feed/");
```

### Result

```html
<b>Fatal error</b>:  Uncaught Zend\Feed\Reader\Exception\RuntimeException: DOMDocument cannot parse XML: Entity 'eacute' not defined
```

The feed is not mine, but doesn't look wrong.

**Comment by froschdesign** [comment]
@middleJack 
> …but doesn't look wrong.

The feed uses a character entity reference from HTML:

```xml
<title>Ej&eacute;rcitos</title>
```

However, a feed is an XML document that does not know HTML entities. XML uses "predefined entities" and these are the known 5:  `quot`, `amp`, `apos`, `lt`, `gt`. All other entities must be defined in a DTD.
(Can be checked in any IDE or in any better editor.)

For the current feed it must be the numeric character entity or the normal letter itself:

```xml
<title>Ej&#233;rcitos</title>
```
```xml
<title>Ejércitos</title>
```

Use [PHP's `html_entity_decode`](https://php.net/manual/function.html-entity-decode.php) function to convert character entity references from HTML before you import the feed.

**Comment by froschdesign** [comment]
You can also check a feed with the W3C feed validator: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.ejercitos.org%2Ffeed

**Comment by middleJack** [comment]
Thank you for your patience, i added the line and now it starts showing another error :(

```html
Fatal error: Uncaught Zend\Feed\Reader\Exception\RuntimeException: DOMDocument cannot parse XML: xmlParseEntityRef: no name in /vendor/zendframework/zend-feed/src/Reader/Reader.php:345 Stack trace: #0 /var/www/test.php(58): Zend\Feed\Reader\Reader::importString('<?xml version="...') #1 {main} thrown in /var/www/vendor/zendframework/zend-feed/src/Reader/Reader.php on line 345
```

Updated code:

```php
<?php
use Zend\Feed\Reader\Reader;
use Zend\Feed\Reader\Exception\RuntimeException;

function curl ($url, $method = "get", $data = []) {
    $ch = curl_init($url);
    $header = [];
    $header[0]  = "Accept: text/xml,application/xml,application/xhtml+xml,";
    $header[0] .= "text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5";
    $header[]   = "Cache-Control: max-age=0";
    $header[]   = "Connection: keep-alive";
    $header[]   = "Keep-Alive: 300";
    $header[]   = "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7";
    $header[]   = "Accept-Language: en-us,en;q=0.5";
    $header[]   = "Pragma: "; // browsers keep this blank.
    curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US; rv:1.8.1.7) Gecko/20070914 Firefox/2.0.0.7');
    curl_setopt($ch, CURLOPT_HTTPHEADER, $header);


    switch ($method)
    {
        case "post":
            curl_setopt($ch, CURLOPT_POST, true);
            if (sizeof($data) > 0) {
                curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
            }
            break;
        case "put":
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
            if (sizeof($data) > 0) {
                curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
            }
            break;
        default:
            if (sizeof($data) > 0) {
                $url = $url . "?" . http_build_query($data);
            }
            break;
    }
    curl_setopt($ch, CURLOPT_ENCODING, '');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_AUTOREFERER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_URL, $url);
    $content = curl_exec($ch);

    return $content;
}

$xml = curl("http://www.ejercitos.org/feed/");

$xml = html_entity_decode($xml); // some websites use html entities in xml (https://github.com/zendframework/zend-feed/issues/106)

Reader::importString($xml);
```

**Comment by froschdesign** [comment]
@middleJack 
Try the following:

```php
// Get the feed
$feedString = file_get_contents('http://www.ejercitos.org/feed/');

// Clean up the XML
$tidy = new tidy;
$tidy->parseString(
    $feedString,
    [
        'input-xml'  => true,
        'output-xml' => true,
    ],
    'utf8'
);
$tidy->cleanRepair();

// Import the feed as string
Zend\Feed\Reader\Reader::importString((string) $tidy);
```

**Comment by froschdesign** [comment]
@middleJack 
> `Fatal error: Uncaught Zend\Feed\Reader\Exception\RuntimeException: DOMDocument cannot parse XML: xmlParseEntityRef: no name in /vendor/zendframework/zend-feed/src/Reader/Reader.php:345 Stack trace: #0 /var/www/test.php(58): Zend\Feed\Reader\Reader::importString('<?xml version="...') #1 {main} thrown in /var/www/vendor/zendframework/zend-feed/src/Reader/Reader.php on line 345`

The problem is here `&` and therefore my previous idea with `html_entity_decode` is not good.

**Comment by middleJack** [comment]
Thank you so much!
I'm always having problems when working with XML. 

Your example is working fine, i will take a look at what is `tidy`, i didn't know about it.
So you recommend always filtering code through `tidy` before going to the parser to make sure it is valid?

I wish rss feeds were jsons.

**Comment by froschdesign** [comment]
`tidy` has many options for cleaning, repairing and transformations. zend-feed already uses `tidy` in `Zend\Feed\Writer\Renderer\Entry\Atom`:

https://github.com/zendframework/zend-feed/blob/f31376bf1d16525e13a82a7498e5dc0cc65fba43/src/Writer/Renderer/Entry/Atom.php#L386-L397

More to `tidy`:

* https://php.net/manual/book.tidy.php
* http://tidy.sourceforge.net/docs/quickref.html

**Comment by froschdesign** [comment]
@middleJack 
This issue report is used as a reference and motivation to think about a decorator for the feed-reader that cleans up invalid / broken XML before starting any further processing.

Thanks for reporting!
