### ISSUE TITLE
Writer: Add support for other content types than xhtml

### ISSUE THREAD

**Issue by danmichaelo** [zendframework/zend-feed#11]
Seems like Zend Feed is hard-coded to produce XHTML content. Would be cool if one could set content type to produce feed content like this

``` xml
<content>
   <content type="text/json">
       {"firstName"="John","lastName"="Doe","id"="10"}
   </content>
   <type>text/json</type>
</content>
```

**Comment by weierophinney** [comment]
@danmichaelo It's hard-coded to generate _valid_ feeds: RSS and Atom. If you're wanting a different type, you will need to extend the component, as we have no plans or desire to support beyond these two types.
