### ISSUE TITLE
Aliases incorrect when adding extensions

### ISSUE THREAD

**Issue by Synchro** [zendframework/zend-feed#30]
I'm following the example of adding extensions from [the docs](https://docs.zendframework.com/zend-feed/reader/#extending-feed-and-entry-apis), where it gives this example:

``` php
$extensions = new ExtensionPluginManager();
$extensions->setInvokableClass('JungleBooksEntry', JungleBooks\Entry::class);
Reader::setExtensionManager(new ExtensionManager($extensions));
Reader::registerExtension('JungleBooks');
```

The call to `setInvokableClass` creates an entry in the `ServiceManager`'s `aliases` array, along with the stock extensions:

``` php
array (
  'atomentry' => 'Zend\\Feed\\Reader\\Extension\\Atom\\Entry',
  'atomEntry' => 'Zend\\Feed\\Reader\\Extension\\Atom\\Entry',
  'AtomEntry' => 'Zend\\Feed\\Reader\\Extension\\Atom\\Entry',
  'atomfeed' => 'Zend\\Feed\\Reader\\Extension\\Atom\\Feed',
//...
  'wellformedwebentry' => 'Zend\\Feed\\Reader\\Extension\\WellFormedWeb\\Entry',
  'wellFormedWebEntry' => 'Zend\\Feed\\Reader\\Extension\\WellFormedWeb\\Entry',
  'WellFormedWebEntry' => 'Zend\\Feed\\Reader\\Extension\\WellFormedWeb\\Entry',
  'JungleBooksEntry' => 'JungleBooks\\Entry',
)
```

This is understandable, but in `Zend\Feed\Reader\Reader::registerExtension`, it creates a map of feed and entry aliases by appending `\Feed` or `\Entry` to the name:

``` php
    public static function registerExtension($name)
    {
        $feedName  = $name . '\Feed';
        $entryName = $name . '\Entry';
```

This is wrong - it does not match the names used in the Service manager's aliases array, so it causes this error:

```
PHP Fatal error:  Uncaught exception 'Zend\Feed\Reader\Exception\RuntimeException' with message 'Could not load extension: JungleBooks using Plugin Loader. Check prefix paths are configured and extension exists.' in vendor/zendframework/zend-feed/src/Reader/Reader.php:580
```

If I change `Reader` to this, it works:

``` php
    public static function registerExtension($name)
    {
        $feedName  = $name . 'Feed';
        $entryName = $name . 'Entry';
```

PR to follow

**Comment by Synchro** [comment]
Hm. It appears that the built-in stuff is dependent on this behaviour - fixing one breaks the other. `StandaloneExtensionManager` preloads the list like this, _with_ slashes:

```
    private $extensions = [
        'Atom\Entry'            => 'Zend\Feed\Reader\Extension\Atom\Entry',
        'Atom\Feed'             => 'Zend\Feed\Reader\Extension\Atom\Feed',
        'Content\Entry'         => 'Zend\Feed\Reader\Extension\Content\Entry',
```

but this is not compatible with the non-standalone extension manager which omits slashes. This is chicken and egg - if you call `setInvokableClass` with just `JungleBooks` as the name, `Reader` will create it own mapping correctly, but it will be wrong in the extensions manager, but if you create it as `JungleBooksEntry`, it will work in the extensions manager, but break in `Reader` (where it will look for `JungleBooksEntry\Entry`). I'm not sure of the best fix for this, I'll scrap my PR.

**Comment by Synchro** [comment]
I've managed to find a workaround that works for both patterns. By ensuring that `ExtensionPluginManager` contains both name types in its aliases array, it works for both naming schemes. I've altered it like this:

``` php
        'atomentry'            => Extension\Atom\Entry::class,
        'atomEntry'            => Extension\Atom\Entry::class,
        'AtomEntry'            => Extension\Atom\Entry::class,
        'Atom\Entry'           => Extension\Atom\Entry::class,
        'atomfeed'             => Extension\Atom\Feed::class,
        'atomFeed'             => Extension\Atom\Feed::class,
        'AtomFeed'             => Extension\Atom\Feed::class,
        'Atom\Feed'            => Extension\Atom\Feed::class,
```

This seems like the wrong approach, but it's workable for now. The right solution would be to make the `ExtensionPluginManager` and `StandaloneExtensionManager` use the same format.

**Comment by Synchro** [comment]
I found another aspect of the same problem. To make my extension work both ways, I need to register it under both names:

```
$extensions->setInvokableClass('JungleBooksEntry', JungleBooks\Entry::class);
$extensions->setInvokableClass('JungleBooks\Entry', JungleBooks\Entry::class);
```

**Comment by Synchro** [comment]
Annoyingly I can't seem to work around this without modifying the library. If I subclass `ExtensionPluginManager` with a fixed `aliases` property, then pass an instance of that class to `Reader::setExtensionManager`, it still breaks - there must be a hard-coded reference to the original class somewhere that bypasses my subclass.

**Comment by pensiero** [comment]
@Synchro maybe it's related to this? https://github.com/zendframework/zend-feed/issues/29

**Comment by Synchro** [comment]
Might be, but I don't get that error.

**Comment by Xerkus** [comment]
@Synchro  Does it work with `$extensions->setInvokableClass('JungleBooks\Entry', JungleBooks\Entry::class);` only?
It looks like a case of outdated documentation due to service manager v3 changes

**Comment by Synchro** [comment]
See [my earlier comment](https://github.com/zendframework/zend-feed/issues/30#issuecomment-244916285) - if you only use one of those definitions it breaks in the other context; you have to do both for it to work in both places.

**Comment by Xerkus** [comment]
@Synchro did i get it right, that problem is actually with existing extensions when using ExtensionPluginManager?
Would you like to make PR for aliases and PR for documentation?

**Comment by Synchro** [comment]
I don't really know enough about ZF to do anything constructive - As I said, the right solution would be to make the `ExtensionPluginManager` and `StandaloneExtensionManager` use the same format, but I have no idea what other complications there might be, or what other code might depend on these things. I'm not using much of ZF at all, I'm just trying to use Zend_Feed and have ended up here!

Documenting the need to do the same thing 2 different ways seems like a bad approach!

**Comment by Xerkus** [comment]
@demiankatz you were using zend-feed, can you take a look at the issue here?

**Comment by demiankatz** [comment]
@Xerkus, I'm spending a lot of time at conferences in the near future, but I'll put this on my to-do list and look at it when I'm caught up on everything. It may be a few weeks, but I'm happy to take this on if nobody else gets there first.

@Synchro, it sounds to me like you can work around your problem for now by pinning zend-servicemanager to version 2 instead of version 3 in your composer.json. If this is the only Zend component you are working on, it shouldn't make much difference for you. Obviously, we need to fix this problem so everything works properly in both versions, but you shouldn't have to wait for our resolution to get things working on your end. If pinning to ServiceManager 2 doesn't help, please let us know since that may indicate that we're misdiagnosing something... but I'm pretty confident it will work.

**Comment by demiankatz** [comment]
Thanks, @Xerkus; sorry I couldn't get to this more quickly.
