### ISSUE TITLE
getAuthor() function not working correctly for RSS feed.

### ISSUE THREAD

**Issue by k-cogswell** [zendframework/zend-feed#36]
I have been using the [Drupal 8 Feeds module](https://www.drupal.org/project/feeds) and encountered an issue when interacting with zend-feed. I am using an XML feed that has a `<author>` field and it is not being handled correctly by the getAuthor() function.

I have made an alteration to /vendor/zendframework/zend-feed/src/Reader/Entry/Rss.php

```
/**
     * Get an author entry
     *
     * @param int $index
     * @return string
     */
    public function getAuthor($index = 0)
    {
        $author = $this->xpath->evaluate('string(' . $this->xpathQueryRss . '/author)');
        return $author;
    }
```

The changes above fixed my problem and the `<author>` field is now importing correctly.

**Comment by froschdesign** [comment]
@k-cogswell 
> The changes above fixed my problem and the <author> field is now importing correctly.

With your changes you ignore the `index` and break the unit tests. Have a look at all these tests: https://github.com/zendframework/zend-feed/blob/master/test/Reader/Feed/RssTest.php#L758

> I am using an XML feed that has a <author> field and it is not being handled correctly by the getAuthor() function.

Can you provide the original RSS feed with the author field? At the moment, I can not reproduce the problem.

**Comment by k-cogswell** [comment]
@froschdesign 

I have attached an example item from the RSS feed I am using. 

[RSS_Example.txt](https://github.com/zendframework/zend-feed/files/810671/RSS_Example.txt)

**Comment by froschdesign** [comment]
@k-cogswell 
1. The feed is wrong, because the value of `author` is not an email address. (see at the [RSS 2.0 specification](http://www.rssboard.org/rss-specification#ltauthorgtSubelementOfLtitemgt))
2. `zend-feed` [checks](https://github.com/zendframework/zend-feed/blob/master/src/Reader/Entry/Rss.php#L114) for an email address.
