### ISSUE TITLE
How feed reader deals with non utf-8 encoding ?

### ISSUE THREAD

**Issue by rajjanorkar** [zendframework/zend-feed#46]
Hi Team,

I am implementing zend-feed reader in my app, i quickly checked the code and documentation and i am not sure or missed something about utf-8 encoding, how feed reader dealing with non utf-8 encoding feeds?

What i need to do is to convert non utf-8 encoding to utf-8 encoding and then store the feed to database.

Any help will be really appreciated. Thank you.

**Comment by froschdesign** [comment]
@rajjanorkar 
> …how feed reader dealing with non utf-8 encoding feeds?

The reader works with the given encoding. Example:

```php
/** @var Zend\Feed\Reader\Feed\AbstractFeed $feed */
$feed = Zend\Feed\Reader\Reader::importString(
    '<?xml version="1.0" encoding="iso-8859-15" ?>
    <rss version="2.0"><channel></channel></rss>'
);

var_dump($feed->getEncoding()); // Output: iso-8859-15
```

> What i need to do is to convert non utf-8 encoding to utf-8 encoding…

This is outside the scope of a feed reader.
