### ISSUE TITLE
Help Wanted : Is Zend Reader better than any other reader out there?

### ISSUE THREAD

**Issue by rajjanorkar** [zendframework/zend-feed#48]
Hi Team,

First apologise for asking question in Issues tab, ( i did not find any other place to ask this question) so here.

I am particularly looking forward to use Zend Reader functionality (i don't need writer or pubsub** etc).

I came across many github repos one famous is [simplepie rss](https://github.com/simplepie/simplepie), as i am totally confused which one i should use. I am more inclined to use zend reader but saying this just based on popularity and contributors here are far more than any other reader out there.

As  you guys might already aware of other feed readers out there as one of that is simplepie, could you please provide some technical comparison which one i should go for and why it is best choice. ( so it is like comparison between zend reader and simplepie )

This will help many other developers who are looking for feed reader, and will be easy to choose.

This is question not an issue but i will really appreciate you guys help here. (please don't close this issue, let other developer share their views on it)

Thank you,
Raj

**Comment by froschdesign** [comment]
@rajjanorkar 
Please use the forum for this kind of question. Thanks!

https://discourse.zendframework.com/

**Comment by Ocramius** [comment]
Cross-linking
https://discourse.zendframework.com/t/is-zend-feed-reader-better-than-any-other-reader-out-there/329

**Comment by rajjanorkar** [comment]
Thank you @froschdesign for pointing me to right direction.
Thank you @Ocramius for answering.
