### ISSUE TITLE
Add translate content to utf-8 encoding feature

### ISSUE THREAD

**Issue by rajjanorkar** [zendframework/zend-feed#59]
Many feeds are not UTF-8 and so we have issues storing those into DB, before storing we need to translate it to UTF-8, this is not supported in zend-feed.

Can we add feature which will detect the content encoding and translate it to utf-8?

**Comment by froschdesign** [comment]
@rajjanorkar 
You have already asked this question: #46

**Comment by rajjanorkar** [comment]
@froschdesign sorry i completely forgotten about it.

**Comment by froschdesign** [comment]
Duplicate of #46
