### ISSUE TITLE
iTunes podcast spec updates

### ISSUE THREAD

**Issue by OpenHaus** [zendframework/zend-feed#66]
There have been numerous changes to Apple´s podcast spec for itunes.

To support the new features in iOS 11, we've updated the Apple Podcasts specification by:

- Enabling providers to deliver clear, concise titles.
- Improving how episodes are ordered and recommended within a season.
- Adding the ability for new subscribers to receive the full current season in their Library.
- Adding quick play to allow users to pick up listening where they left off.

See https://itunespartner.apple.com/en/podcasts/news/41700009 and https://help.apple.com/itc/podcasts_connect/#/itcb54353390

These are the new tags currently not supported by Zend Feed:

Channel:
`<itunes:type>`
`<itunes:complete>`

Show:
`<itunes:episode>`
`<itunes:episodeType>`

Furthermore `<itunes:keywords>` is now deprecated.

**Comment by froschdesign** [comment]
Good catch! 👍
