### ISSUE TITLE
Add Google Podcast extension

### ISSUE THREAD

**Issue by OpenHaus** [zendframework/zend-feed#67]
Google integrated Podcast support into the play store last year. [1]

Accompanying they also published a few tags to optimize the podcast listing. [2]

It would be nice to see this supported by Zend Feed as an extension.

[1] https://support.google.com/googleplaymusic/answer/6343833?hl=en
[2] https://developers.google.com/search/docs/data-types/podcast

**Comment by froschdesign** [comment]
The tags are similar to iTunes. Example:

```
<googleplay:block>
    yes
</googleplay:block>
          OR
<itunes:block>
    yes
</itunes:block>
```

https://developers.google.com/search/docs/data-types/podcast#podcast-level-rss-tags

**Comment by weierophinney** [comment]
Thanks, @chrisdeeming.

**Comment by michalbundyra** [comment]
@froschdesign why this is reopened?

**Comment by froschdesign** [comment]
@webimpress 
This issue doesn't belongs to #68. (@weierophinney used the wrong number in the commit message)
