### ISSUE TITLE
Zend-Feed Reader : Not checking empty response from source - so throwing exception

### ISSUE THREAD

**Issue by rajjanorkar** [zendframework/zend-feed#70]
Hi Team,

There is bug in reader because not checking the empty string when we import feed

I am trying to import : [http://feeds.feedburner.com/people/headlines](http://feeds.feedburner.com/people/headlines)

somehow this feed is returning empty string, so i think in reader we should check the response if empty then we should handle it programatically. 

### Code to reproduce the issue

```
$feed = Zend\Feed\Reader\Reader::import('http://feeds.feedburner.com/people/headlines');
$data = [
    'title'        => $feed->getTitle(),
    'link'         => $feed->getLink(),
    'dateModified' => $feed->getDateModified(),
    'description'  => $feed->getDescription(),
    'language'     => $feed->getLanguage(),
    'entries'      => [],
];
```

### Expected results

Ideally it should not throw an exception.

### Actual results

```
exception 'Zend\Feed\Reader\Exception\InvalidArgumentException' with message 'Only non empty strings are allowed as input' in /home/example/vendor/zendframework/zend-feed/src/Reader/Reader.php:319
#0 /home/example/vendor/zendframework/zend-feed/src/Reader/Reader.php(266): Zend\Feed\Reader\Reader::importString('')
#1 /home/example/app/Reader/FeedLoaderService.php(90): Zend\Feed\Reader\Reader::import('http://feeds.fe...')
```

Thank you

**Comment by froschdesign** [comment]
Please look at the error message, the reader checks already for empty strings. Catch the exception and all is fine.
