### ISSUE TITLE
iTunes Podcast Spec - Missing itunes:image for entries

### ISSUE THREAD

**Issue by OpenHaus** [zendframework/zend-feed#76]
There has been an `<itunes:image>` tag for ages in Apple´s podcast spec. Apple makes use of these images in iTunes and the Podcast app. Also more and more other apps support this.

From the Apple documenation at https://help.apple.com/itc/podcasts_connect/#/itcb54353390

`<itunes:image>`

The episode artwork.

Specify your episode artwork using the `<a href>` attribute in the `<itunes:image>` tag. ...

This is basically the same implementation as for the channel in Writer/Extension/ITunes/Renderer/Feed.php just for the Writer/Extension/ITunes/Renderer/Entry.php

### Code to implement

```php

    /**
     * Set feed image (icon)
     *
     * @param  DOMDocument $dom
     * @param  DOMElement $root
     * @return void
     */
    // @codingStandardsIgnoreStart
    protected function _setImage(DOMDocument $dom, DOMElement $root)
    {
        // @codingStandardsIgnoreEnd
        $image = $this->getDataContainer()->getItunesImage();
        if (! $image) {
            return;
        }
        $el = $dom->createElement('itunes:image');
        $el->setAttribute('href', $image);
        $root->appendChild($el);
        $this->called = true;
    }
```

### Expected results

It would add an image to an item/entry:

```php
<item>
    <itunes:image href="https://example.org/logo.jpg">
</item>
```

Would be really nice to have this implemented!

**Comment by weierophinney** [comment]
Fixed with #77; will release with 2.10.0.
