### ISSUE TITLE
PHPDoc for EntryInterface::getAuthor is incorrect

### ISSUE THREAD

**Issue by Synchro** [zendframework/zend-feed#83]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-feed/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-feed/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

My IDE flagged a type mismatch on the results of a call to `Entry::getAuthor()` when there shouldn't be one.

### Code to reproduce the issue

[This line](https://github.com/zendframework/zend-feed/blob/master/src/Reader/Entry/EntryInterface.php#L20) declares the interface for `getAuthor` as returning `string|null`, and the implementation in the Rss class declares [it returns a string](https://github.com/zendframework/zend-feed/blob/master/src/Reader/Entry/Rss.php#L69) (and doesn't mention `null`), but it really returns an associative array containing a single `name` element, because it returns a single element of the return value of `getAuthors()`, as seen in [this implementation](https://github.com/zendframework/zend-feed/blob/master/src/Reader/Entry/Rss.php#L97) in the `Rss` class.

The Atom class does [something similar](https://github.com/zendframework/zend-feed/blob/master/src/Reader/Entry/Atom.php#L73), but it's not quite the same as it doesn't build the assoc array with the `name` element, so it may actually be returning a string (I don't know exactly what `$this->getExtension('Atom')->getAuthors()` returns).

The PHPDocs need to be made consistent, and/or the function needs to be modified so it really does return a string and not an array. Altering the return type would be a BC break, even though it's not meant to work that way, so I suspect the PHPdoc change would be more appropriate.

**Comment by froschdesign** [comment]
It's an array:

https://github.com/zendframework/zend-feed/blob/54dffde2554cb2f12a57343d8c2d8db21161b6ec/test/Reader/Entry/AtomTest.php#L213-L238

https://github.com/zendframework/zend-feed/blob/54dffde2554cb2f12a57343d8c2d8db21161b6ec/test/Reader/Entry/RssTest.php#L981-L988
