### ISSUE TITLE
Zend Feed and Feed.io

### ISSUE THREAD

**Issue by Isinlor** [zendframework/zend-feed#88]
Hello,

First of all, I'm really grateful for all the work that went into Zend Feed.

I'm currently in process of developing an [open-source RSS Reader with some smart futures on top](https://gitlab.com/DeepRSS/Reader). Basically opposite of Facebook feed i.e. instead of hiding how news are selected I want to make it possible to play with all parameters of algorithms that are useful in news selection.

That having said, I have recently found https://feed-io.net and I'm considering switching to it.

Seems like maintainer of that project is able to invest significantly more time into it, than Zend Feed maintainers are.

I have some questions / propositions:
1. Do you think Zend Feed covers features that Feed.io does not?
2. Would you consider joining efforts? Or at least consider adding a link in readme to the other project?

Again, I know how much work it cost to build something and I'm grateful for your efforts :+1: .

**Comment by froschdesign** [comment]
I'm sorry, but this is an issue-tracker. Please use the [forum](https://discourse.zendframework.com/) or [chat](https://zendframework-slack.herokuapp.com/) for questions. Thanks!
