### ISSUE TITLE
Issue with invalid entry IDs (isPermaLink not set to false)

### ISSUE THREAD

**Issue by glen-84** [zendframework/zend-feed#89]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-feed/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-feed/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

We're using entry IDs like `news-27`. `Zend\Feed\Uri#isValid` is returning `true` for these IDs, and `isPermaLink` is therefore not being set to `false`.

This results in the feed not validating:

```
line 16, column 19: guid must be a full URL, unless isPermaLink attribute is false: news-27 (10 occurrences) [help]

      <guid>news-27</guid>
```

### Code to reproduce the issue

```php
$entry->setId('news-27');
```

### Expected results

These IDs are not valid [URLs](http://www.rssboard.org/rss-profile#data-types-url), and therefore `isPermaLink` should be set to `false`.

### Actual results

`isPermaLink` is not set.

**Comment by froschdesign** [comment]
@glen-84 
> `Zend\Feed\Uri#isValid` is returning true for these IDs…

Can you provide an unit test which illustrates the problem? At the moment I can not reproduce the problem. Thanks!

**Comment by glen-84** [comment]
@froschdesign,

What does the following code output for you?

```php
use Zend\Feed\Uri;

var_dump(Uri::factory('news-27')->isValid());
```

**Comment by froschdesign** [comment]
@glen-84 
In the meantime, I wanted to write an unit test myself, but there is no test class for `Zend\Feed\Uri`! I think this should be ported from [zend-uri](https://github.com/zendframework/zend-uri/blob/master/test/UriTest.php).

I do not know why Atom and RSS are handled differently here:
https://github.com/zendframework/zend-feed/blob/8a54f0e8fbafba349749d956c40d3cb4c0710522/src/Writer/Renderer/Entry/Atom.php#L287-L295

https://github.com/zendframework/zend-feed/blob/8a54f0e8fbafba349749d956c40d3cb4c0710522/src/Writer/Renderer/Entry/Rss.php#L299-L301

Btw. the class includes a method [`isAbsolute`](https://github.com/zendframework/zend-feed/blob/8a54f0e8fbafba349749d956c40d3cb4c0710522/src/Uri.php#L180) which can be help.

**Comment by froschdesign** [comment]
@glen-84 
Can you test #99? Thanks in advance!

**Comment by glen-84** [comment]
@froschdesign It works! 🎉 Thanks a lot.

(apologies for the late reply)

**Comment by froschdesign** [comment]
@glen-84 
No problem. Can you look at #90 and give me a feedback?
